#VARIABLES EN PYTHON
# - NO DEBE TENER CARACTER RARO A MENOS _
# - NO DEBE EMPEZAR CON UN NUMERO
# - NO DEBE TENER ESPACIOS

#UNA VARIABLE PUEDE SER UN TIPO DETERMINADO.
#INT (INTEGER) NUMERO SIN DECIMALES
#FLOAT (PUNTO FLOTANTE) NUMERO CON DECIMALES
#STRING (CADENA DE TEXTO)
#BOOLEANO (BOOL) LOGICO EJE: True or False

#area de variables
nombre=""
print ("Ingrese su nombre:")
nombre=input()
print ("Hola ", nombre)
